name: PR and Commit Message Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1️⃣ PR title & description validation
      - name: Validate PR title and description
        run: |
          echo "🔍 Validating PR title and description..."
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"

          if [ -z "$PR_TITLE" ] || [ -z "$PR_BODY" ]; then
            echo "❌ PR title or description is missing."
            exit 1
          fi

          echo "✅ PR title and description are valid."

      # 2️⃣ Commit message validation for dev-1.0.0-* branches
      - name: Validate commit messages for developer branch
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-$(git rev-parse --abbrev-ref HEAD)}"
          echo "Current branch: $BRANCH_NAME"

          # Check if branch matches dev-1.0.0-<developername>
          if [[ ! "$BRANCH_NAME" =~ ^dev-1\.0\.0-[a-zA-Z0-9_-]+$ ]]; then
            echo "ℹ️ Skipping commit message validation (branch does not match dev-1.0.0-<developername> format)"
            exit 0
          fi

          echo "🔍 Validating commit messages in branch: $BRANCH_NAME"
          git fetch origin $BRANCH_NAME || true

          # Get commits in PR range
          COMMITS=$(git log --format=%s origin/${{ github.event.pull_request.base.ref }}..HEAD)

          if [ -z "$COMMITS" ]; then
            echo "⚠️ No new commits found to validate."
            exit 0
          fi

          while read -r COMMIT_MSG; do
            [ -z "$COMMIT_MSG" ] && continue

            echo "Checking: $COMMIT_MSG"

            # Length check (>50 characters)
            if [ ${#COMMIT_MSG} -le 50 ]; then
              echo "❌ Commit message must be more than 50 characters."
              exit 1
            fi

            # Task ID format check
            if ! echo "$COMMIT_MSG" | grep -qE '#[0-9]{5,7}'; then
              echo "❌ Commit message must include a task ID in format: #<5–7 digits>"
              exit 1
            fi

          done <<< "$COMMITS"

          echo "✅ All commit messages passed checks."
