name: PR & Commit Message Validation

on:
  pull_request:
    branches:
      - dev-1.0.0

jobs:
  validate-pr-and-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ------------------------
      # 1. PR Title & Description Check
      # ------------------------
      - name: Check PR title and description length
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          BODY="${{ github.event.pull_request.body }}"

          echo "🔍 Checking PR title length..."
          if [ ${#TITLE} -le 30 ]; then
            echo "❌ PR title must be more than 30 characters. Current length: ${#TITLE}"
            exit 1
          fi

          echo "🔍 Checking PR description length..."
          if [ ${#BODY} -le 100 ]; then
            echo "❌ PR description must be more than 100 characters. Current length: ${#BODY}"
            exit 1
          fi

          echo "✅ PR title and description meet requirements."

      # ------------------------
      # 2. Commit Message Check
      # ------------------------
      - name: Check commit messages
        run: |
          echo "🔍 Validating commit messages in this PR..."
          COMMITS=$(git log --format=%s origin/${{ github.base_ref }}..HEAD)

          while read -r COMMIT_MSG; do
            echo "Checking: $COMMIT_MSG"

            # Length check
            if [ ${#COMMIT_MSG} -le 50 ]; then
              echo "❌ Commit message must be more than 50 characters."
              echo "Message: $COMMIT_MSG"
              exit 1
            fi

            # Task ID format check
            if ! echo "$COMMIT_MSG" | grep -Eq '#[0-9]{5,7}'; then
              echo "❌ Commit message must include a task ID in format: #<5–7 digits>"
              echo "Message: $COMMIT_MSG"
              exit 1
            fi

          done <<< "$COMMITS"

          echo "✅ All commit messages passed checks."