name: PR Title & Description Validation

on:
  pull_request:
    branches:
      - dev-1.0.0   # target branch for PRs

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title and description length
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          BODY="${{ github.event.pull_request.body }}"

          echo "🔍 Checking PR title length..."
          if [ ${#TITLE} -le 30 ]; then
            echo "❌ PR title must be more than 30 characters. Current length: ${#TITLE}"
            exit 1
          fi

          echo "🔍 Checking PR description length..."
          if [ ${#BODY} -le 100 ]; then
            echo "❌ PR description must be more than 100 characters. Current length: ${#BODY}"
            exit 1
          fi

          echo "✅ PR title and description meet requirements."
